### ISSUE TITLE
Comminication Protocol

### ISSUE THREAD

**Issue by garry572** [oxynatOr/esphome-pytes_e_box#8]
Hi

Im in the process of installing a Pytes battery 4 X 5kwh, so Im keen to follow your integration into Home Assistant

Any further information you might have aquired would be helpfull/interesting

**Comment by oxynatOr** [comment]
im sorry i have my hand broken, so i cant really wirte :(

best is u start with his: 
https://github.com/oxynatOr/esphome-pytes_e_box/blob/main/examples/pytes_e_box-full.yaml

or tell me where you have problems, typing with oner hand is :(

**Comment by garry572** [comment]
I have quick go at installing it in HA 2025.4.3, it complaining that is doesnt know what a "text_sensor" I will investiagte further. maybe  Ive done in done something in haste

**Comment by oxynatOr** [comment]
> I have quick go at installing it in HA 2025.4.3, it complaining that is doesnt know what a "text_sensor" I will investiagte further. maybe Ive done in done something in haste

ok i will try todo a full tutorial.

**Comment by oxynatOr** [comment]
> I have quick go at installing it in HA 2025.4.3, it complaining that is doesnt know what a "text_sensor" I will investiagte further. maybe Ive done in done something in haste

try this:
```yaml
esphome:

esp32:

wifi:
  ap:

logger:

api:

ota:

external_components:
  - source: github://oxynatOr/esphome-pytes_e_box
    components: [ pytes_e_box ]
    refresh: 5s

packages:
  pytes_ebox_1: 
    url: https://github.com/oxynatOr/esphome-pytes_e_box
    files:
      - path: examples/packages/pytesebox-monitor.yaml
        vars:
          pytes_e_box_id: pvbatt
          battery_num: 1
          cell_prefix: "Cell"
          battery_prefix: "Battery"
  pytes_ebox_2: 
    url: https://github.com/oxynatOr/esphome-pytes_e_box
    files:
      - path: examples/packages/pytesebox-monitor.yaml
        vars:
          pytes_e_box_id: pvbatt
          battery_num: 2
          cell_prefix: "Cell"
          battery_prefix: "Battery"     

uart:
  tx_pin: GPIO5
  rx_pin: GPIO6
  baud_rate: 115200
  rx_buffer_size: 1024
  id: uart01   

pytes_e_box:
  - id: pvbatt
    uart_id: uart01
    update_interval: 30s
    batteries: 2
    poll_timeout: 4s 
    command_idle_time: 150ms


```

**Comment by garry572** [comment]
Thanks for that. works great, just have to wait for the batterys to be installed

**Comment by garry572** [comment]
Thanks for you help Ive finally got the batteries installed and working, I have these error messages, it appears the firmware in my batteries aret not fully supported I do get the messges i want, howver the flood of retrys slow the update rate to something like 5 minutes.
Is there any easy way to fix this, Im reluctant to go too far, as I suspect I could/will make the issue worse
Any help much appreciated, and a great job

[20:27:25][D][sensor:104]: 'Battery 1 Work Status': Sending state 2.00000  with 0 decimals of accuracy
[20:27:25][D][sensor:104]: 'Battery 1 Cells': Sending state 16.00000  with 0 decimals of accuracy
[20:27:25][W][component:407]: pytes_e_box took a long time for an operation (70 ms)
[20:27:25][W][component:408]: Components should block for at most 30 ms
[20:27:25][C][pytes_e_box:143]:   Commands in Queue: [index:0, command: "pwr"] [index:1, command: "pwr 1"] [index:1, command: "bat 1"] [index:2, command: "pwr 2"] [index:2, command: "bat 2"]
[20:27:25][D][pytes_e_box:145]: Sending command from queue: bat 1 from index: 2
[20:27:25][D][pytes_e_box:317]: parsed command -> Not in List [Battery: 1]
[20:27:25][I][pytes_e_box:110]: Retrying command 'bat 1' from index: 2, retry count: 0, at time: 10412 ms
[20:27:25][D][pytes_e_box:317]: parsed command -> Not in List [Battery: 1]
[20:27:25][I][pytes_e_box:110]: Retrying command 'bat 1' from index: 2, retry count: 1, at time: 10601 ms
[20:27:26][D][pytes_e_box:317]: parsed command -> Not in List [Battery: 1]
[20:27:26][I][pytes_e_box:110]: Retrying command 'bat 1' from index: 2, retry count: 2, at time: 10790 ms
[20:27:26][D][pytes_e_box:317]: parsed command -> Not in List [Battery: 1]
[20:27:26][I][pytes_e_box:110]: Retrying command 'bat 1' from index: 2, retry count: 3, at time: 11082 ms
[20:27:26][D][pytes_e_box:317]: parsed command -> Not in List [Battery: 1]
[20:27:26][I][pytes_e_box:110]: Retrying command 'bat 1' from index: 2, retry count: 4, at time: 11270 ms

**Comment by oxynatOr** [comment]
> Thanks for you help Ive finally got the batteries installed and working, I have these error messages, it appears the firmware in my batteries aret not fully supported I do get the messges i want, howver the flood of retrys slow the update rate to something like 5 minutes. Is there any easy way to fix this, Im reluctant to go too far, as I suspect I could/will make the issue worse Any help much appreciated, and a great job
> 
> [20:27:25][D][sensor:104]: 'Battery 1 Work Status': Sending state 2.00000 with 0 decimals of accuracy [20:27:25][D][sensor:104]: 'Battery 1 Cells': Sending state 16.00000 with 0 decimals of accuracy [20:27:25][W][component:407]: pytes_e_box took a long time for an operation (70 ms) [20:27:25][W][component:408]: Components should block for at most 30 ms [20:27:25][C][pytes_e_box:143]: Commands in Queue: [index:0, command: "pwr"] [index:1, command: "pwr 1"] [index:1, command: "bat 1"] [index:2, command: "pwr 2"] [index:2, command: "bat 2"] [20:27:25][D][pytes_e_box:145]: Sending command from queue: bat 1 from index: 2 [20:27:25][D][pytes_e_box:317]: parsed command -> Not in List [Battery: 1] [20:27:25][I][pytes_e_box:110]: Retrying command 'bat 1' from index: 2, retry count: 0, at time: 10412 ms [20:27:25][D][pytes_e_box:317]: parsed command -> Not in List [Battery: 1] [20:27:25][I][pytes_e_box:110]: Retrying command 'bat 1' from index: 2, retry count: 1, at time: 10601 ms [20:27:26][D][pytes_e_box:317]: parsed command -> Not in List [Battery: 1] [20:27:26][I][pytes_e_box:110]: Retrying command 'bat 1' from index: 2, retry count: 2, at time: 10790 ms [20:27:26][D][pytes_e_box:317]: parsed command -> Not in List [Battery: 1] [20:27:26][I][pytes_e_box:110]: Retrying command 'bat 1' from index: 2, retry count: 3, at time: 11082 ms [20:27:26][D][pytes_e_box:317]: parsed command -> Not in List [Battery: 1] [20:27:26][I][pytes_e_box:110]: Retrying command 'bat 1' from index: 2, retry count: 4, at time: 11270 ms

i assume the config is correct?


```
uart:
  tx_pin:  gpio pin you use
  rx_pin: gpio pin you use
  baud_rate: 115200
  rx_buffer_size: 1024
  id: uart01   

pytes_e_box:
  - id: pvbatt
    uart_id: uart01
    update_interval: 30s
    batteries: 4
    poll_timeout: 4s 
    command_idle_time: 150ms
``` 

do you know the fw ref of the batteries? 

i have one on  ```SPBMS16SRPV1.5.26.C16.T5```amd two on ```SPBMS16SRP2205V1.5.18.C16.T3```

with no issues.  


you use a ESP32? someone told me an esp8266 isn't good for this.
